version: '3.7'
services:
  db:
    image: mysql:latest
    container_name: neo-chess
    restart: always
    environment:
      MYSQL_DATABASE: 'neo-chess-database'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'Serek123'
      MYSQL_ROOT_PASSWORD: 'SerekRootBez123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./docker-files/db:/var/lib/mysql
      
volumes:
  my-db:
  