version: '3.7'
services:
  db:
    image: mysql:latest
    container_name: neo-chess-db
    restart: always
    environment:
      MYSQL_DATABASE: 'neo-chess-database'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'Serek123'
      MYSQL_ROOT_PASSWORD: 'SerekRootBez123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./support/docker-files/db:/var/lib/mysql
  backend:
    build: 
      context: ./
      dockerfile: ./support/backend.dockerfile
    container_name: neo-chess-backend
    restart: always
    ports:
      - '5000:5000'
    expose:
      - '5000'
  frontend:
    build: 
      context: ./
      dockerfile: ./support/frontend.dockerfile
    container_name: neo-chess-frontend
    restart: always
    ports:
      - '3000:3000'
    expose:
      - '3000'