version: '3.7'

services:
  db:
    image: mysql:8.0.29
    container_name: NeoChessDatabase
    environment:
      MYSQL_DATABASE: 'neo-chess-database'
      MYSQL_USER: 'neochess_431429'
      MYSQL_PASSWORD: 'FmHnqBd2lsnC'
      MYSQL_ROOT_PASSWORD: '0OW5y35zxPIO6nAypcY'
    volumes:
      - ./docker-files/db:/var/lib/mysql
    networks:
      - neoNet

  backend:
    container_name: NeoChessBackend
    build:
      dockerfile: Dockerfile.production
      context: "../backEnd"
    ports:
      - 5000:5000
    depends_on:
      - db
    networks:
      - neoNet

  frontend:
    container_name: NeoChessFrontend
    stdin_open: true
    build:
      dockerfile: Dockerfile.production
      context: ../frontEnd
    ports:
      - 80:80
    depends_on:
      - backend

volumes:
  my-db:


networks:
  neoNet:
    ipam:
      driver: default
